# Generated by Django 2.1.2 on 2018-10-20 02:42

from django.db import migrations, models
import vcard.models


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=vcard.models.scramble_uploaded_filename, verbose_name='Uploaded image')),
            ],
        ),
    ]
