# Generated by Django 2.1.2 on 2018-10-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0002_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Thumbnail of uploaded image'),
        ),
    ]
