# Generated by Django 2.1.2 on 2018-10-20 10:44

from django.db import migrations, models
import vcard.models


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0003_uploadedimage_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImage',
        ),
        migrations.RenameField(
            model_name='mvcard',
            old_name='linked',
            new_name='linkedin',
        ),
        migrations.AddField(
            model_name='mvcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=vcard.models.scramble_uploaded_filename, verbose_name='Uploaded image'),
        ),
        migrations.AlterField(
            model_name='mvcard',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
